
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD DIV MUL NUM SUB\n    S : ExpI\n    \n    ExpI : ExpI ADD ExpS\n    \n    ExpI : ExpI SUB ExpS\n    \n    ExpI   : ExpS\n    \n    ExpS : ExpS MUL Termo\n    \n    ExpS : ExpS DIV Termo\n    \n    ExpS   : Termo\n    \n    Termo : NUM\n    '
    
_lr_action_items = {'NUM':([0,6,7,8,9,],[5,5,5,5,5,]),'$end':([1,2,3,4,5,10,11,12,13,],[0,-1,-4,-7,-8,-2,-3,-5,-6,]),'ADD':([2,3,4,5,10,11,12,13,],[6,-4,-7,-8,-2,-3,-5,-6,]),'SUB':([2,3,4,5,10,11,12,13,],[7,-4,-7,-8,-2,-3,-5,-6,]),'MUL':([3,4,5,10,11,12,13,],[8,-7,-8,8,8,-5,-6,]),'DIV':([3,4,5,10,11,12,13,],[9,-7,-8,9,9,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'ExpI':([0,],[2,]),'ExpS':([0,6,7,],[3,10,11,]),'Termo':([0,6,7,8,9,],[4,4,4,12,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> ExpI','S',1,'p_global','exp_sin.py',7),
  ('ExpI -> ExpI ADD ExpS','ExpI',3,'p_expI_add','exp_sin.py',13),
  ('ExpI -> ExpI SUB ExpS','ExpI',3,'p_expI_sub','exp_sin.py',19),
  ('ExpI -> ExpS','ExpI',1,'p_expI_expS','exp_sin.py',25),
  ('ExpS -> ExpS MUL Termo','ExpS',3,'p_expS_mul','exp_sin.py',31),
  ('ExpS -> ExpS DIV Termo','ExpS',3,'p_expS_div','exp_sin.py',37),
  ('ExpS -> Termo','ExpS',1,'p_expS_termo','exp_sin.py',43),
  ('Termo -> NUM','Termo',1,'p_termo','exp_sin.py',49),
]
